var _i_repository_validation_interceptor_factory_8java =
[
    [ "ca.uhn.fhir.jpa.starter.common.validation.IRepositoryValidationInterceptorFactory", "interfaceca_1_1uhn_1_1fhir_1_1jpa_1_1starter_1_1common_1_1validation_1_1_i_repository_validation_interceptor_factory.html", "interfaceca_1_1uhn_1_1fhir_1_1jpa_1_1starter_1_1common_1_1validation_1_1_i_repository_validation_interceptor_factory" ]
];