var _repository_validation_interceptor_factory_r4_8java =
[
    [ "ca.uhn.fhir.jpa.starter.common.validation.RepositoryValidationInterceptorFactoryR4", "classca_1_1uhn_1_1fhir_1_1jpa_1_1starter_1_1common_1_1validation_1_1_repository_validation_interceptor_factory_r4.html", "classca_1_1uhn_1_1fhir_1_1jpa_1_1starter_1_1common_1_1validation_1_1_repository_validation_interceptor_factory_r4" ]
];